# Use Python base image
FROM python:3.12.0-alpine

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apk add --no-cache gcc musl-dev python3-dev

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the gRPC port
EXPOSE 50051

# Run the gRPC server
CMD ["python", "server.py"]